name:                clasificacion
version:             0.1.0.0
github:              "githubuser/clasificacion"
license:             BSD3
author:              "Juan Miguel Vilar Torres"
maintainer:          "juan.miguel.vilar@gmail.com"
copyright:           "2017 Juan Miguel Vilar Torres"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/clasificacion#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  clasificacion-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clasificacion
    - cassava
    - optparse-applicative

tests:
  clasificacion-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clasificacion
